buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.4'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    compileSdkVersion = 28
    minSdkVersion = 19
    targetSdkVersion = 19
    buildToolsVersion = '28.0.3'
}

